### ISSUE TITLE
2.0.4.dev open dep on execjs

### ISSUE THREAD

**Issue by stevenolen** [WebBlocks/WebBlocks#70]
Mostly just submitting an issue in case anyone else runs into this

The 2.0.4.dev build has an open dependency on execjs and some interaction between bower and execjs 2.6 causes `blocks build` to fail with the stack trace below.

Adding the more pessimistic dependency in the project's gemfile itself fixes this (you might need a `bundle update execjs` if you've already locked past 2.2.2..):
`gem 'execjs', '~> 2.2'`

```
[39m/var/lib/jenkins/.rvm/gems/ruby-2.1.1/gems/execjs-2.6.0/lib/execjs/external_runtime.rb:39:in `exec': TypeError: Cannot call method 'on' of undefined (ExecJS::ProgramError)[31m
>> [39m    from /var/lib/jenkins/.rvm/gems/ruby-2.1.1/gems/execjs-2.6.0/lib/execjs/external_runtime.rb:14:in `initialize'[31m
>> [39m    from /var/lib/jenkins/.rvm/gems/ruby-2.1.1/gems/execjs-2.6.0/lib/execjs/runtime.rb:44:in `new'[31m
>> [39m    from /var/lib/jenkins/.rvm/gems/ruby-2.1.1/gems/execjs-2.6.0/lib/execjs/runtime.rb:44:in `compile'[31m
>> [39m    from /var/lib/jenkins/.rvm/gems/ruby-2.1.1/gems/ruby-bower-0.0.1/lib/ruby-bower/ruby-bower.rb:15:in `context'[31m
>> [39m    from /var/lib/jenkins/.rvm/gems/ruby-2.1.1/bundler/gems/WebBlocks-e208bb3afae7/lib/web_blocks/manager/bower.rb:34:in `clean_components_cache!'[31m
>> [39m    from /var/lib/jenkins/.rvm/gems/ruby-2.1.1/bundler/gems/WebBlocks-e208bb3afae7/lib/web_blocks/manager/bower.rb:47:in `clean_install!'[31m
>> [39m    from /var/lib/jenkins/.rvm/gems/ruby-2.1.1/bundler/gems/WebBlocks-e208bb3afae7/lib/web_blocks/thor/base/prepare_blocks.rb:72:in `block in install_bower_components!'[31m
>> [39m    from /var/lib/jenkins/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/logger.rb:372:in `add'[31m
>> [39m    from /var/lib/jenkins/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/logger.rb:400:in `debug'[31m
>> [39m    from /var/lib/jenkins/.rvm/gems/ruby-2.1.1/bundler/gems/WebBlocks-e208bb3afae7/lib/web_blocks/support/scoped_logger.rb:44:in `block (2 levels) in <class:ScopedLogger>'[31m
>> [39m    from /var/lib/jenkins/.rvm/gems/ruby-2.1.1/bundler/gems/WebBlocks-e208bb3afae7/lib/web_blocks/thor/base/prepare_blocks.rb:71:in `install_bower_components!'[31m
>> [39m    from /var/lib/jenkins/.rvm/gems/ruby-2.1.1/bundler/gems/WebBlocks-e208bb3afae7/lib/web_blocks/thor/base/prepare_blocks.rb:39:in `block in prepare_blocks!'[31m
>> [39m    from /var/lib/jenkins/.rvm/gems/ruby-2.1.1/bundler/gems/WebBlocks-e208bb3afae7/lib/web_blocks/support/scoped_logger.rb:27:in `scope'[31m
>> [39m    from /var/lib/jenkins/.rvm/gems/ruby-2.1.1/bundler/gems/WebBlocks-e208bb3afae7/lib/web_blocks/thor/base/prepare_blocks.rb:34:in `prepare_blocks!'[31m
>> [39m    from /var/lib/jenkins/.rvm/gems/ruby-2.1.1/bundler/gems/WebBlocks-e208bb3afae7/lib/web_blocks/thor/build/all.rb:19:in `all'[31m
>> [39m    from /var/lib/jenkins/.rvm/gems/ruby-2.1.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'[31m
>> [39m    from /var/lib/jenkins/.rvm/gems/ruby-2.1.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'[31m
>> [39m    from /var/lib/jenkins/.rvm/gems/ruby-2.1.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'[31m
>> [39m    from /var/lib/jenkins/.rvm/gems/ruby-2.1.1/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'[31m
>> [39m    from /var/lib/jenkins/.rvm/gems/ruby-2.1.1/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'[31m
>> [39m    from /var/lib/jenkins/.rvm/gems/ruby-2.1.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'[31m
>> [39m    from /var/lib/jenkins/.rvm/gems/ruby-2.1.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'[31m
>> [39m    from /var/lib/jenkins/.rvm/gems/ruby-2.1.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'[31m
>> [39m    from /var/lib/jenkins/.rvm/gems/ruby-2.1.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'[31m
>> [39m    from /var/lib/jenkins/.rvm/gems/ruby-2.1.1/bundler/gems/WebBlocks-e208bb3afae7/bin/blocks:5:in `<top (required)>'[31m
>> [39m    from /var/lib/jenkins/.rvm/gems/ruby-2.1.1/bin/blocks:23:in `load'[31m
>> [39m    from /var/lib/jenkins/.rvm/gems/ruby-2.1.1/bin/blocks:23:in `<main>'[31m
>> [39m    from /var/lib/jenkins/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'[31m
>> [39m    from /var/lib/jenkins/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by stevenolen** [comment]
This was fixed in b82e1898f0d41f09ad961357c7195f817282a130, but doesn't apply to `2.0.4.dev` (which we needed to stick to for some compatibility with existing projects).
